### ISSUE TITLE
Will it support fragment lifecycle?

### ISSUE THREAD

**Issue by kyze8439690** [stephanenicolas/loglifecycle#1]
Thanks for your library which is very useful, will it support fragment lifecycle log in the future?

**Comment by stephanenicolas** [comment]
Sure ! I just need some time, or some help from contributors. I believe this should be pretty straightforward.

**Comment by stephanenicolas** [comment]
Support for Fragment (native and support), activities, services, broadcast receiver and application has been added to loglifecycle 1.0.1. Should hit central within 2 hours.
